# Generated by Django 2.2.1 on 2019-06-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('F_Name', models.CharField(max_length=100)),
                ('Roll_No', models.PositiveIntegerField(unique=True)),
                ('Board', models.CharField(max_length=100)),
                ('Marks', models.PositiveIntegerField()),
                ('Condition', models.CharField(max_length=100)),
                ('Selected', models.BooleanField(default=False)),
            ],
        ),
    ]
