# Generated by Django 2.2.2 on 2019-07-04 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedStd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('F_Name', models.CharField(max_length=100)),
                ('Roll_No', models.PositiveIntegerField(unique=True)),
                ('Address', models.CharField(max_length=100)),
                ('Marks', models.PositiveIntegerField()),
                ('Contact', models.PositiveIntegerField()),
                ('FIELDS', models.CharField(choices=[('Medical', 'Medical'), ('Engineering', 'Engineering'), ('Computer Science', 'Computer Science'), ('Humanite', 'Humanite')], max_length=20)),
                ('Condition', models.CharField(choices=[('OPEN', 'OPEN'), ('LOCAL', 'LOCAL')], default='OPEN', max_length=10)),
                ('Entry_Date', models.DateTimeField(default=datetime.datetime(2019, 7, 4, 21, 41, 0, 323545, tzinfo=utc))),
                ('Selected', models.BooleanField(default=True)),
                ('Selected_Date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-Marks',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('F_Name', models.CharField(max_length=100)),
                ('Roll_No', models.PositiveIntegerField(unique=True)),
                ('Address', models.CharField(max_length=100)),
                ('Marks', models.PositiveIntegerField()),
                ('Contact', models.PositiveIntegerField()),
                ('FIELDS', models.CharField(choices=[('Medical', 'Medical'), ('Engineering', 'Engineering'), ('Computer Science', 'Computer Science'), ('Humanite', 'Humanite')], default='Medical', max_length=20)),
                ('Condition', models.CharField(choices=[('OPEN', 'OPEN'), ('LOCAL', 'LOCAL')], default='OPEN', max_length=10)),
                ('Entry_Date', models.DateTimeField(default=datetime.datetime(2019, 7, 4, 21, 41, 0, 320547, tzinfo=utc))),
                ('Selected', models.BooleanField(blank=True, default=False, null=True)),
                ('Selected_Date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-Marks',),
            },
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
