# Generated by Django 2.2.2 on 2019-07-05 08:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190705_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedstd',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 8, 5, 59, 162696, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 8, 5, 59, 162696, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Roll_No',
            field=models.PositiveIntegerField(),
        ),
    ]
