# Generated by Django 2.2.2 on 2019-07-06 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190705_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedstd',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 17, 16, 16, 692906, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 17, 16, 16, 677141, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Roll_No',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
