# Generated by Django 2.2.2 on 2019-07-06 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190706_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedstd',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 17, 25, 45, 802708, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='selectedstd',
            name='Roll_No',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 17, 25, 45, 802708, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Roll_No',
            field=models.PositiveIntegerField(),
        ),
    ]
