# Generated by Django 2.2.2 on 2019-07-06 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190706_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedstd',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 17, 27, 1, 822624, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 17, 27, 1, 822624, tzinfo=utc)),
        ),
    ]
