# Generated by Django 2.2.2 on 2019-07-06 19:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190706_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedstd',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 19, 31, 44, 91654, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='selectedstd',
            name='FIELDS',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Engineering', 'Engineering'), ('Computer Science', 'Computer Science'), ('Humanities', 'Humanities')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 19, 31, 44, 91654, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='FIELDS',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Engineering', 'Engineering'), ('Computer Science', 'Computer Science'), ('Humanities', 'Humanities')], default='Medical', max_length=20),
        ),
    ]
