# Generated by Django 3.1 on 2020-08-07 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200807_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedstd',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 7, 38, 40, 280678, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 7, 38, 40, 278674, tzinfo=utc)),
        ),
    ]
